### Support vector machines

### PRoblem Statement: Business wants us to build a model that prescribes the Drug to respective patient based on their medical condition



### Data Gathering

In [1]:
path = r"https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/drug200.csv"
import pandas as pd
df = pd.read_csv(path)
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    str
 2   BP           200 non-null    str
 3   Cholesterol  200 non-null    str
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 9.5 KB

In [3]:
df.shape

(200, 6)

### Separate X and Y

In [4]:
X = df.drop(columns='Drug')
Y = df[['Drug']]

In [5]:
X.head()

   Age Sex      BP Cholesterol  Na_to_K
0   23   F    HIGH        HIGH   25.355
1   47   M     LOW        HIGH   13.093
2   47   M     LOW        HIGH   10.114
3   28   F  NORMAL        HIGH    7.798
4   61   F     LOW        HIGH   18.043

In [6]:
Y.head()

    Drug
0  DrugY
1  drugC
2  drugC
3  drugX
4  DrugY

### Splitting of data: training and testing
    training : 85% testing: 15%

In [7]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,train_size=0.85,random_state=21)

In [8]:
print(xtrain.shape)
print(xtest.shape)

(170, 5)
(30, 5)

### Data Preprocessing and Data cleaning

In [12]:
# change the directory of current folder to package created at Repository folder
import os
path2 = r"C:\ml files\repository\Preparing_data\Preparing_data"
# consider path until repository - r"E:\Sindhura\Machine Learning 1535\repository"
os.chdir(r"C:\ml files\repository\Preparing_data")

In [13]:
# from package_name.module_name import function(method)
from Preparing_data.data_cleaning_processing import cleaning_preprocessing_cat_con

ModuleNotFoundError: No module named 'Preparing_data'